### ISSUE TITLE
Running bash script run_qp4ewc_script.sh produces incorrect results

### ISSUE THREAD

**Issue by pvrqualitasag** [sknqualitasag/qp4ewc#9]
When running bash-script `run_qp4ewc_script.sh` the result files look different than when the R-function `qp4ewc::pre_process_ewbc_input()` is called directly. As an example the beginning of the incorrect outputfile PARA.TXT looks as follows

`$ head work/LM_2_Natura-Beef/PARA.TXT 
"Comment:
    Calculation for example data, December 2013"
1
2
  (1 Closed purebred beef cow herd with pasture system producing males and
     females for replacement
   2 Closed crossbred cow herd with pasture system producing its own female 
     replacement but buying the breeding bulls
   3 Open beef x dairy or beef x dual purpose crossbred cow herd with pasture
     system with purchase of cow and bull replacement)"`

The correct version should be

`$ head /tmp/RtmpjDWWAE/qw4ewc/work/LM_2_Natura-Beef/PARA.TXT
"Comment:
    Calculation for example data, December 2013"
2
"Production System
  (1 Closed purebred beef cow herd with pasture system producing males and
     females for replacement
   2 Closed crossbred cow herd with pasture system producing its own female 
     replacement but buying the breeding bulls
   3 Open beef x dairy or beef x dual purpose crossbred cow herd with pasture
     system with purchase of cow and bull replacement)"`

**Comment by pvrqualitasag** [comment]
Line-by-line debugging revealed that the problem occurs on line 170 in function `pre_process_ewbc_input()`. After executing the following call:

`  qp4ewc::update_input_parameter_file(ps_path2template_input_parameter_file = file.path(ps_path_directory2create,paste0(ps_sirebreed,"_",ps_prodsystew,"_",ps_marketchannel),l_constants_ewbc_input_beefOnbeef$file_par),
                                      ps_statement2search = l_constants_ewbc_input_beefOnbeef$prodsyst,
                                      ps_value2update = l_constants_ewbc_input_beefOnbeef$prodsyst2,
                                      pb_log,
                                      plogger = lgr)`

The file PARA.TXT has the incorrect format.

**Comment by sknqualitasag** [comment]
This issue is solved with the merging of the branch beefOndairy
